//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFremeWorkProcess2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFilmler
    {
        public int FilmID { get; set; }
        public string FilmAd { get; set; }
        public string FilmYonetmen { get; set; }
        public Nullable<short> TurID { get; set; }
        public string FilmSure { get; set; }
        public Nullable<bool> FilmYerli { get; set; }
        public string FilmKonu { get; set; }
        public string FilmYil { get; set; }
        public Nullable<bool> Film3D { get; set; }
        public string FilmAfisResim { get; set; }
        public Nullable<bool> FilmArsiv { get; set; }
    }
}
