//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFinalTekrar1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_YedekParcaOtomasyonSistemiEntities : DbContext
    {
        public Db_YedekParcaOtomasyonSistemiEntities()
            : base("name=Db_YedekParcaOtomasyonSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MusteriYedekParcaListesi> MusteriYedekParcaListesi { get; set; }
        public virtual DbSet<Tblithalat> Tblithalat { get; set; }
        public virtual DbSet<TblMarkaModel> TblMarkaModel { get; set; }
        public virtual DbSet<TblMusteri> TblMusteri { get; set; }
        public virtual DbSet<TblParcaAlisBilgi> TblParcaAlisBilgi { get; set; }
        public virtual DbSet<TblYedekParca> TblYedekParca { get; set; }
        public virtual DbSet<Tblilceler> Tblilceler { get; set; }
        public virtual DbSet<Tbliller> Tbliller { get; set; }
    }
}
