//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFinalTekrar1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriYedekParcaListesi
    {
        public int ID { get; set; }
        public string TCNO { get; set; }
        public string YedekParcaKod { get; set; }
        public Nullable<short> alis_adet { get; set; }
        public Nullable<double> toplam_fiyat { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblYedekParca TblYedekParca { get; set; }
    }
}
