//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFinalTekrar1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMusteri()
        {
            this.MusteriYedekParcaListesi = new HashSet<MusteriYedekParcaListesi>();
        }
    
        public string tcno { get; set; }
        public string resimyol { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string cep_telefonu { get; set; }
        public string ev_telefonu { get; set; }
        public string eposta { get; set; }
        public string ev_adresi { get; set; }
        public Nullable<bool> ban { get; set; }
        public string ban_aciklama { get; set; }
        public Nullable<bool> arsiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriYedekParcaListesi> MusteriYedekParcaListesi { get; set; }
    }
}
