//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFinalTekrar1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblParcaAlisBilgi
    {
        public int ParcaAlisID { get; set; }
        public Nullable<int> IthalatID { get; set; }
        public string YedekParcaKod { get; set; }
        public Nullable<short> AlisAdeti { get; set; }
        public Nullable<double> AlisFiyat { get; set; }
        public string AlisTarih { get; set; }
    
        public virtual Tblithalat Tblithalat { get; set; }
        public virtual TblYedekParca TblYedekParca { get; set; }
    }
}
