//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFinalTekrar1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYedekParca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblYedekParca()
        {
            this.MusteriYedekParcaListesi = new HashSet<MusteriYedekParcaListesi>();
            this.TblParcaAlisBilgi = new HashSet<TblParcaAlisBilgi>();
        }
    
        public string YedekParcaKod { get; set; }
        public string YedekParcaAd { get; set; }
        public string YedekParcaKategori { get; set; }
        public Nullable<double> YedekParcaSatisFiyat { get; set; }
        public Nullable<short> YedekParcaAdet { get; set; }
        public Nullable<int> MarkaModelID { get; set; }
        public string YedekParcaAciklama { get; set; }
        public Nullable<bool> Arsiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriYedekParcaListesi> MusteriYedekParcaListesi { get; set; }
        public virtual TblMarkaModel TblMarkaModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblParcaAlisBilgi> TblParcaAlisBilgi { get; set; }
    }
}
