//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaTakipOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet_Tablo
    {
        public int satisno { get; set; }
        public string filmad { get; set; }
        public string filmtarih { get; set; }
        public string filmseans { get; set; }
        public string koltukno { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string ucret { get; set; }
        public Nullable<bool> Archive { get; set; }
    }
}
